server:
  port: 8090

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookportalproject
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true



management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, metrics

